sonar.projectKey=culture-web_culture-web-be
sonar.organization=culture-web
sonar.sources=controllers,routes,services,client,utils,middleware,config,server.js
sonar.tests=tests
sonar.cpd.exclusions=tests/**
sonar.coverage.exclusions=tests/**,node_modules/**
